### ISSUE TITLE
Problems when using mpv --vo=kitty

### ISSUE THREAD

**Issue by arb103** [sergei-grechanik/st-graphics#4]
### Problem
Running `mpv --vo=kitty filename` works, but the output drops a lot of frames.
The recommended solution to this is to use `--vo-kitty-use-shm=yes`, but doing so results in: `EINVAL: transmission medium 's' is not supported  in command: a=T,t=s,f=24,s=1050,v=590,C=1,q=2,m=1`
### Expected behaviour
mpv to have a working and faster video output by using /dev/shm
### Attempted solutions
I admit that the following is me just probing blindly, but maybe there is some valuable information in my dumb efforts
I can see the EINVAL error string on `graphics.c:3224` in function gr_handle_transmit_command
```c
			"EINVAL: transmission medium '%c' is not supported",
```
I couldn't find where it could be being called with 's' as the value for transmission_medium, so I tried adding the following to graphics.c
```c
	ImageFrame *frame = NULL;
	if (cmd->transmission_medium == 'f' ||
	    cmd->transmission_medium == 't' ||
	    cmd->transmission_medium == 's') {
```
and the error changed to
`EBADF: No such file or directory  in command: a=T,t=s,f=24,s=1050,v=590,C=1,q=2,m=1
Could not load the file mpv-kitty-0x55f7d4797c60`
when I checked in /dev/shm/ I verified that such file did, in fact, exist
so I checked how the directory for files was used and found that a tempdir is made in /tmp/st-images-XXXXXX
I changed `config.def.h:179` to
```c
const char graphics_cache_dir_template[] = "/dev/shm";
```
and `graphics.c:1893:1899` to:
```c
//	if (!mkdtemp(cache_dir)) {
//		fprintf(stderr,
//			"error: could not create temporary dir from template "
//			"%s\n",
//			sanitized_filename(cache_dir));
//		return 0;
//	}
```
Now, on startup, st prints `Graphics cache directory: /dev/shm`, but the EBADF error remains
I tried one last thing, undoing my first change and instead doing `graphics.c:3199`:
```c
	} else if (cmd->transmission_medium == 'd' || cmd->transmission_medium == 's') {
```
Now there are no errors but also no output.
### Conclusion
If this is something I should take up with the mpv devs I'll gladly do so, but this looked like the right place to start.
Thank you for your wonderful fork.

**Comment by sergei-grechanik** [comment]
yeah, transmission over shared memory is not supported yet. I'll probably look into it over the weekend. However, my implementation is just slower than kitty's, so it might not be enough for good fps, but we'll see.

**Comment by sergei-grechanik** [comment]
I've just pushed a preliminary implementation. It's much smoother now, but still not as smooth as kitty, and performance degrades quickly with higher resolutions. It can be optimized further, but I'll probably need to redesign the image transmission implementation.

**Comment by arb103** [comment]
Just tried it and it works perfectly, 0 frames dropped.
If you think you can make it more efficient, go ahead, but this works great for me.
Thank you very much.

**Comment by sergei-grechanik** [comment]
Just a couple of notes:
- I've just pushed a patch to unlink the shm file on the terminal side, as required by the protocol. It seems to cause artifacts with mpv if the resolution is too high (black horizontal lines). Not sure what's going on, I want to blame mpv that reuses the same shm name for each frame, which may cause the frame being overwritten before it's read and the frame being dropped because the shm may be unlinked just before it's sent to the terminal. However, it's not clear to me how it can cause the artifacts I'm observing.
- There are three main optimization opportunities:
  1) Stop writing the data to a file before loading the image.
  2) gr_load_pixmap does image resizing, but it may be skipped if the size is already correct.
  3) gr_copy_pixels takes quite a long time, compiling with `-O2` helps a lot, but it can definitely be optimized further.
